# Generated by Django 5.2.17 on 2026-09-24 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm_numero', models.CharField(max_length=40, verbose_name='número de ATM')),
                ('periodo', models.DateField(help_text='Usa el primer día del mes, por ejemplo 2026-09-01.', verbose_name='mes (primer día)')),
                ('cierre', models.DateTimeField(blank=True, null=True, verbose_name='fecha y hora de cierre')),
                ('observacion_cierre', models.TextField(blank=True, db_default='', default='')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mantenimientos',
                'ordering': ['atm_numero'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora de atención')),
                ('observacion', models.TextField(max_length=3000, verbose_name='observación')),
                ('registrado_el', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='seguimiento.mantenimiento')),
            ],
            options={
                'verbose_name': 'atención',
                'verbose_name_plural': 'atenciones',
                'db_table': 'atenciones',
                'ordering': ['fecha_hora', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='responsable')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responsables',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='responsable',
            field=models.ForeignKey(db_column='responsable', on_delete=django.db.models.deletion.PROTECT, to='seguimiento.responsable'),
        ),
        migrations.AddConstraint(
            model_name='responsable',
            constraint=models.CheckConstraint(condition=models.Q(('codigo__in', ['ROMINA', 'DANNESY', 'ROSAURA'])), name='responsable_conocido'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['responsable', 'periodo'], name='mantenimien_respons_928eb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='mantenimiento',
            constraint=models.UniqueConstraint(fields=('atm_numero', 'periodo'), name='un_atm_por_mes'),
        ),
        migrations.AddConstraint(
            model_name='mantenimiento',
            constraint=models.CheckConstraint(condition=models.Q(('atm_numero', ''), _negated=True), name='atm_no_vacio'),
        ),
    ]
